"""Reconstruct day-of-cycle from mcPHASES and emit smoothed canonical 28-day
curves the app uses for a precise per-day status.

Cycle day is rebuilt per patient by detecting menstrual onset (first day of a
Menstrual run) and counting forward. Validated signals only (cramps, resting
HR, HRV, progesterone) — steps/sleep/stress are excluded (not cycle-linked).

Run:  python3 scripts/build_cycle_day_data.py
"""
import json
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DF_PATH = ROOT / "data" / "patient_day.parquet"
OUT_PATH = ROOT / "lib" / "cycleDayData.ts"

PHASES = ["Menstrual", "Follicular", "Fertility", "Luteal"]
SEV = {"Not at all": 0, "Very Low": 1, "Very Low/Little": 1, "Low": 2, "Moderate": 3, "High": 4, "Very High": 5}
NOTABLE = {"Moderate", "High", "Very High"}
CANON = 28  # canonical cycle length for the baked curves


def reconstruct(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for pid, g in df.sort_values(["id", "day_in_study"]).groupby("id"):
        prev, onset = None, None
        for _, r in g.iterrows():
            ph = r["phase"]
            if ph == "Menstrual" and prev != "Menstrual":
                onset = r["day_in_study"]
            if onset is not None and ph in PHASES:
                cd = int(r["day_in_study"] - onset + 1)
                if 1 <= cd <= CANON:
                    rows.append((pid, cd, r["cramps"], r["resting_heart_rate"], r["hrv_rmssd_mean"], r["pdg"]))
            prev = ph
    return pd.DataFrame(rows, columns=["id", "cd", "cramps", "rhr", "hrv", "pdg"])


def smooth(series: pd.Series) -> list[float]:
    # length-CANON, reindexed 1..CANON, rolling mean window 3, edges filled
    s = series.reindex(range(1, CANON + 1)).interpolate(limit_direction="both")
    return [round(float(v), 2) for v in s.rolling(3, center=True, min_periods=1).mean()]


def main() -> None:
    df = df = pd.read_parquet(DF_PATH)
    c = reconstruct(df)
    c["cramps_n"] = c["cramps"].map(SEV)
    c["cramps_notable"] = c["cramps"].isin(NOTABLE)

    by = c.groupby("cd")
    cramps_pct = smooth((by["cramps_notable"].mean() * 100))
    rhr = smooth(by["rhr"].mean())
    hrv = smooth(by["hrv"].mean())
    pdg = smooth(by["pdg"].mean())
    n_per_day = by.size().reindex(range(1, CANON + 1)).fillna(0).astype(int).tolist()

    data = {
        "canonicalLength": CANON,
        "crampsPct": cramps_pct,      # % logging moderate+ cramps, by cycle day
        "restingHr": rhr,             # bpm, by cycle day
        "hrv": hrv,                   # ms RMSSD, by cycle day
        "progesterone": pdg,          # PDG, by cycle day
        "samplesPerDay": n_per_day,
        "rhrMin": round(min(rhr), 1),
        "rhrMax": round(max(rhr), 1),
        "crampsPeakDay": int(np.argmax(cramps_pct) + 1),
        "samplePatients": int(c["id"].nunique()),
    }

    body = json.dumps(data, indent=2)
    ts = (
        "// AUTO-GENERATED by scripts/build_cycle_day_data.py from the mcPHASES dataset.\n"
        "// Do not edit by hand. Per-cycle-day curves (canonical 28-day), validated signals only.\n"
        "// Day-of-cycle reconstructed from menstrual onsets; arrays are index 0 = cycle day 1.\n\n"
        "export type CycleDayData = {\n"
        "  canonicalLength: number;\n"
        "  crampsPct: number[];\n"
        "  restingHr: number[];\n"
        "  hrv: number[];\n"
        "  progesterone: number[];\n"
        "  samplesPerDay: number[];\n"
        "  rhrMin: number;\n"
        "  rhrMax: number;\n"
        "  crampsPeakDay: number;\n"
        "  samplePatients: number;\n"
        "};\n\n"
        f"export const CYCLE_DAY_DATA: CycleDayData = {body} as const;\n"
    )
    OUT_PATH.write_text(ts, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    print("crampsPeakDay:", data["crampsPeakDay"], "rhr range:", data["rhrMin"], "-", data["rhrMax"])
    print("samples/day:", n_per_day)


if __name__ == "__main__":
    main()
