#!/usr/bin/env python3
"""Curate data/combined/food_scored.csv -> lib/foodBank.ts
A compact, PCOS-scored food bank the plan LLM builds meals from.
Run: python3 scripts/build_food_bank.py"""
import pandas as pd, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]               # ovara-mobile/
SRC  = ROOT / "data/food_scored.csv"                     # vendored in-repo build input
OUT  = ROOT / "lib/foodBank.ts"

def nz(v):
    """NaN/None -> 0.0 (note: `NaN or 0` returns NaN in Python)."""
    return 0.0 if pd.isna(v) else float(v)

PER_ROLE = 36          # top foods kept per meal-role
MIN_SCORE = 40         # drop clearly poor foods

# categories to drop entirely (processed / not plan-relevant)
DROP_CATS = {"Baby Foods", "Fast Foods", "Restaurant Foods", "Sweets", "Snacks",
             "Sausages and Luncheon Meats", "Meals, Entrees, and Side Dishes",
             "American Indian/Alaska Native Foods", "Spices and Herbs", "Beverages"}

ANIMAL_CATS = {"Beef Products", "Pork Products", "Poultry Products",
               "Lamb, Veal, and Game Products", "Finfish and Shellfish Products",
               "Sausages and Luncheon Meats"}
DAIRY_EGG_CAT = "Dairy and Egg Products"

DAIRY_KW = re.compile(r"\b(milk|cheese|butter|yogurt|yoghurt|cream|whey|ghee|custard|kefir)\b", re.I)
EGG_KW   = re.compile(r"\b(egg|eggs)\b", re.I)
MEAT_KW  = re.compile(r"\b(beef|pork|chicken|turkey|lamb|veal|fish|salmon|tuna|shrimp|bacon|ham|sausage|meat|gelatin|anchovy|crab|duck)\b", re.I)
GLUTEN_KW = re.compile(r"\b(wheat|barley|rye|bread|pasta|cracker|cereal|flour|couscous|bulgur|seitan|noodle|tortilla|bran)\b", re.I)
HONEY_KW  = re.compile(r"\bhoney\b", re.I)
# processed/concentrated items that game per-100g scoring — exclude from a whole-food bank
EXCLUDE_KW = re.compile(
    r"(?:powder|dried|dehydrated|supplement|imitation|formula|instant|concentrate|"
    r"muscle milk|ice cream|candies|syrup|nonfat|fat free|fat-free|reduced fat|"
    r"low fat|lowfat|substitute|meal replacement|protein bar|fortified|\bpeel\b)", re.I)

def role_of(cat, desc):
    c = cat or ""
    if c in ("Vegetables and Vegetable Products", "Spices and Herbs"): return "veg"
    if c == "Fruits and Fruit Juices": return "fruit"
    if c == "Legumes and Legume Products": return "protein"
    if c in ANIMAL_CATS: return "protein"
    if c == "Nut and Seed Products": return "nut_seed"
    if c in ("Cereal Grains and Pasta", "Breakfast Cereals"): return "grain"
    if c == DAIRY_EGG_CAT: return "dairy"
    if c == "Fats and Oils": return "fat"
    # fallback by keyword
    if MEAT_KW.search(desc): return "protein"
    return "other"

def diet_flags(cat, desc):
    c = cat or ""
    is_animal = c in ANIMAL_CATS or bool(MEAT_KW.search(desc))
    is_dairy  = c == DAIRY_EGG_CAT and not EGG_KW.search(desc) or bool(DAIRY_KW.search(desc))
    is_egg    = bool(EGG_KW.search(desc)) and not DAIRY_KW.search(desc)
    is_honey  = bool(HONEY_KW.search(desc))
    vegan = not (is_animal or is_dairy or is_egg or is_honey)
    vegetarian = not is_animal
    dairy_free = not is_dairy
    gluten_free = not GLUTEN_KW.search(desc)
    return vegan, vegetarian, dairy_free, gluten_free

def clean_name(s):
    s = re.sub(r"\s+", " ", str(s)).strip()
    return s[:70]

df = pd.read_csv(SRC, low_memory=False)
# keep foods with real macro data
macro = df[["energy_kcal", "protein_g", "carb_g", "fat_g"]].fillna(0).sum(axis=1)
df = df[(macro > 0) & (df.pcos_diet_score >= MIN_SCORE)].copy()
df = df[~df.food_category.isin(DROP_CATS)]
df = df[~df.description.astype(str).str.contains(EXCLUDE_KW)]

rows = []
for _, r in df.iterrows():
    desc = str(r.description)
    cat = r.food_category if isinstance(r.food_category, str) else ""
    role = role_of(cat, desc)
    if role == "other":
        continue
    vegan, vegetarian, dairy_free, gluten_free = diet_flags(cat, desc)
    rows.append({
        "name": clean_name(desc), "score": float(r.pcos_diet_score), "cat": cat or "Other",
        "role": role, "kcal": round(nz(r.energy_kcal)),
        "protein": round(nz(r.protein_g), 1), "fiber": round(nz(r.fiber_g), 1),
        "sugar": round(nz(r.sugar_g), 1),
        "vegan": vegan, "vegetarian": vegetarian, "dairyFree": dairy_free, "glutenFree": gluten_free,
    })
bank = pd.DataFrame(rows)

# dedup near-identical names (first 4 words), then keep top PER_ROLE per role
bank["dedup"] = bank.name.str.lower().str.split().str[:4].str.join(" ")
bank = bank.sort_values("score", ascending=False).drop_duplicates("dedup")
kept = bank.groupby("role", group_keys=False).head(PER_ROLE).drop(columns="dedup")
kept = kept.sort_values(["role", "score"], ascending=[True, False])

items = kept.to_dict("records")
ts = (
    "// AUTO-GENERATED by scripts/build_food_bank.py — do not edit by hand.\n"
    "// Source: data/food_scored.csv (USDA whole foods, PCOS-scored 0-100).\n\n"
    "export type BankFood = {\n"
    "  name: string; score: number; cat: string; role: string;\n"
    "  kcal: number; protein: number; fiber: number; sugar: number;\n"
    "  vegan: boolean; vegetarian: boolean; dairyFree: boolean; glutenFree: boolean;\n"
    "};\n\n"
    f"export const FOOD_BANK: BankFood[] = {json.dumps(items, indent=0)};\n"
)
OUT.write_text(ts)

print("WROTE", OUT)
print("total foods:", len(items))
print("by role:", kept.role.value_counts().to_dict())
print("vegan-ok:", int(kept.vegan.sum()), "| veg-ok:", int(kept.vegetarian.sum()),
      "| gluten-free:", int(kept.glutenFree.sum()), "| dairy-free:", int(kept.dairyFree.sum()))
print("score range:", round(kept.score.min(), 1), "-", round(kept.score.max(), 1))
print("sample top:", [i["name"] for i in items[:6]])
