#!/usr/bin/env python3
"""Distill data/pcos_scored.csv (541-patient cohort) -> lib/pcosGuidance.ts
A few aggregate, evidence-grounded facts for the plan LLM system prompt.
NO raw patient rows are exported. Run: python3 scripts/build_pcos_guidance.py"""
import pandas as pd, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC  = ROOT / "data/pcos_scored.csv"
OUT  = ROOT / "lib/pcosGuidance.ts"

d = pd.read_csv(SRC)
subs = ["hyperandrogenism_score", "cycle_score", "imaging_score",
        "metabolic_score", "hormonal_score", "lifestyle_score"]
by = d.groupby("PCOS_label")[subs + ["pcos_health_score"]].mean().round(1)
neg, pos = by.loc[0], by.loc[1]
gaps = (neg[subs] - pos[subs]).sort_values(ascending=False)
nice = {"hyperandrogenism_score": "hyperandrogenism (hirsutism, acne)",
        "cycle_score": "cycle irregularity", "imaging_score": "ovarian follicle burden",
        "metabolic_score": "metabolic health (BMI, waist:hip, glucose)",
        "hormonal_score": "hormonal balance (AMH, LH:FSH, vitamin D)",
        "lifestyle_score": "lifestyle (diet, exercise)"}
top3 = [nice[k] for k in gaps.index[:3]]

guidance = [
    f"In a 541-patient PCOS cohort scored 0-100 (100=healthiest), PCOS-positive patients "
    f"averaged {pos['pcos_health_score']:.0f} vs {neg['pcos_health_score']:.0f} for negatives.",
    f"The factors that most separated healthier from less-healthy patients were: "
    f"{top3[0]}, {top3[1]}, and {top3[2]}.",
    "Metabolic health and lifestyle are the most modifiable levers — diet and movement "
    "directly improve insulin sensitivity, the core driver of PCOS symptoms.",
    "Favor low-glycemic, high-fiber, anti-inflammatory foods with adequate lean protein; "
    "limit added sugar, refined carbs, saturated and trans fat.",
    "Match movement to cycle phase: gentler restorative work in the menstrual and luteal "
    "phases, more energetic training in the follicular and ovulatory phases.",
]

ts = (
    "// AUTO-GENERATED by scripts/build_pcos_guidance.py — do not edit by hand.\n"
    "// Source: data/pcos_scored.csv (541-patient PCOS cohort). Aggregate facts only.\n\n"
    f"export const PCOS_GUIDANCE: string[] = {json.dumps(guidance, indent=2)};\n\n"
    f"export const COHORT_STATS = {json.dumps({'meanScorePcosPos': float(pos['pcos_health_score']), 'meanScorePcosNeg': float(neg['pcos_health_score']), 'topDiscriminators': top3}, indent=2)};\n"
)
OUT.write_text(ts)
print("WROTE", OUT)
for g in guidance:
    print(" -", g)
