// AUTO-GENERATED by scripts/build_pcos_guidance.py — do not edit by hand.
// Source: data/pcos_scored.csv (541-patient PCOS cohort). Aggregate facts only.

export const PCOS_GUIDANCE: string[] = [
  "In a 541-patient PCOS cohort scored 0-100 (100=healthiest), PCOS-positive patients averaged 59 vs 82 for negatives.",
  "The factors that most separated healthier from less-healthy patients were: hyperandrogenism (hirsutism, acne), cycle irregularity, and ovarian follicle burden.",
  "Metabolic health and lifestyle are the most modifiable levers \u2014 diet and movement directly improve insulin sensitivity, the core driver of PCOS symptoms.",
  "Favor low-glycemic, high-fiber, anti-inflammatory foods with adequate lean protein; limit added sugar, refined carbs, saturated and trans fat.",
  "Match movement to cycle phase: gentler restorative work in the menstrual and luteal phases, more energetic training in the follicular and ovulatory phases."
];

export const COHORT_STATS = {
  "meanScorePcosPos": 59.3,
  "meanScorePcosNeg": 82.2,
  "topDiscriminators": [
    "hyperandrogenism (hirsutism, acne)",
    "cycle irregularity",
    "ovarian follicle burden"
  ]
};
