// AUTO-GENERATED by scripts/build_phase_insights.py from the mcPHASES dataset.
// Do not edit by hand. Re-run the script to refresh.
// Source: PhysioNet mcPHASES v1.0.0 (42 participants, self-report + wearables).

import type { CyclePhase } from './storage';

export type PhaseInsight = {
  status: string;
  headline: string;
  symptoms: { label: string; pct: number }[];
  suggestions: string[];
  stats: { label: string; value: string }[];
  sampleDays: number;
  samplePatients: number;
};

export const PHASE_INSIGHTS: Record<CyclePhase, PhaseInsight> = {
  "menstrual": {
    "status": "Cramps likely — keep warm and rest",
    "headline": "37% logged moderate-or-higher cramps in this phase.",
    "symptoms": [
      {
        "label": "cramps",
        "pct": 37
      },
      {
        "label": "bloating",
        "pct": 45
      }
    ],
    "suggestions": [
      "Warmth and iron-rich foods can soften cramps.",
      "Ease salt and sip warm water or peppermint tea."
    ],
    "stats": [
      {
        "label": "Resting HR",
        "value": "67 bpm"
      },
      {
        "label": "HRV",
        "value": "59 ms"
      }
    ],
    "sampleDays": 1079,
    "samplePatients": 42
  },
  "follicular": {
    "status": "Recovery is strong — a good day to move",
    "headline": "28% logged moderate-or-higher headaches in this phase.",
    "symptoms": [
      {
        "label": "headaches",
        "pct": 28
      }
    ],
    "suggestions": [
      "Hydrate well and watch caffeine to limit headaches.",
      "Recovery is strong here (resting HR ~65 bpm, higher HRV) — a good time to push a little."
    ],
    "stats": [
      {
        "label": "Resting HR",
        "value": "65 bpm"
      },
      {
        "label": "HRV",
        "value": "57 ms"
      }
    ],
    "sampleDays": 1386,
    "samplePatients": 42
  },
  "ovulatory": {
    "status": "Fertile window — energy and libido peak",
    "headline": "40% logged moderate-or-higher sleep trouble in this phase.",
    "symptoms": [
      {
        "label": "sleep trouble",
        "pct": 40
      }
    ],
    "suggestions": [
      "Wind down screen-free; a cooler room helps you settle.",
      "Estrogen and LH peak — your likely fertile window, with energy and libido often highest."
    ],
    "stats": [
      {
        "label": "Resting HR",
        "value": "67 bpm"
      },
      {
        "label": "HRV",
        "value": "54 ms"
      }
    ],
    "sampleDays": 1281,
    "samplePatients": 42
  },
  "luteal": {
    "status": "Lower recovery — favour rest and protein",
    "headline": "36% logged moderate-or-higher food cravings in this phase.",
    "symptoms": [
      {
        "label": "food cravings",
        "pct": 36
      }
    ],
    "suggestions": [
      "Pair cravings with protein to keep blood sugar steady.",
      "Your body works a little harder now (resting HR ~69 bpm, lower HRV) — favour rest and easy movement."
    ],
    "stats": [
      {
        "label": "Resting HR",
        "value": "69 bpm"
      },
      {
        "label": "HRV",
        "value": "52 ms"
      }
    ],
    "sampleDays": 1912,
    "samplePatients": 42
  }
} as const;
